export type PlayerSeed = {
  playerName: string;
  year: number;
  teamAbbr: string;
  position: "PG" | "SG" | "SF" | "PF" | "C";
  games: number;
  mpg: number;
  ppg: number;
  rpg: number;
  apg: number;
  spg: number;
  bpg: number;
  fgPct?: number;
  accolades?: string[];
  allStar?: boolean;
  mvp?: boolean;
  dpoy?: boolean;
  champion?: boolean;
};

/**
 * Full rotation-level corpus (1980–2026, all franchises that existed each year).
 * Generated by `npx tsx scripts/expand-player-db.ts` from Basketball-Reference.
 * Absolute end-of-bench role players (tiny minutes / cup-of-coffee games) are excluded.
 */
import raw from "./players.json";

export const players = raw as PlayerSeed[];
